export const Positions = [
  "abogado",
  "abogado_carpeta",
  "ACHICHINCLE",
  "alertas_uif",
  "archivo",
  "asistente",
  "asistente de porteria",
  "autos",
  "caja",
  "caja_abogado",
  "caja_admin",
  "caja_conciliar",
  "caja_contador",
  "caja_movimientos",
  "caja_notario",
  "caja_tarjetas",
  "caja_vales",
  "Cumplañero",
  "cumpleaños",
  "decenas",
  "ditto",
  "escrituras",
  "expedientes_uif",
  "gestor",
  "gestores df",
  "gestores foraneos",
  "Hoy",
  "IBM",
  "indices",
  "Mesa de Control",
  "notario",
  "Notario_V",
  "pas calle",
  "pas primera",
  "pas registro",
  "pas segunda",
  "pasante",
  "remoto",
  "sec previos",
  "sec protocolo",
  "Sec Recepcion",
  "sistemas",
  "subir_archivos",
  "_rfc"
];

export default {
  Positions
};
